apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: camel
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.5.0
  replicas: 1
  bootstrapServers: 'serverless-kafka-bootstrap.serverless-demo.svc:9092'
  image: 'quay.io/hguerreroo/camel-kafka-connect'
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1